latexmath:[$\(\mathbb{F}_p\)$]

= Glossary for Literature Review

This will be a glossary of terms, equations, and derivations needed to understand material in papers.
So of which, will be review.
== Vocabulary

* *Cross Section:* (sigma) is the area transverse to particles relative motion
within which they must meet in order to scatter from each other. When a cross
section is integrated over all scattering angles (and possibly other variables)
it is called a total cross section.

* *Differential Cross Section:*  When a cross section is specified as a function
 of some final-state variable, such as particle angle or energy.

* *Kinematic Factor:* K = E1/E2 shows that the energy after scattering is only
dependent upon the mass of the 2 particles and the scattering angle of the
incident particle after the collision.

* *Correction Factor:* F, is use to account for scattering interactions outside
1 Bohr radius. In other words, it accounts for the screening caused by interacting
with the electrons in the K and higher electron shells.

* *Reciprocal Lattice* Fourier transform of the Bravais Lattice. The shape of the Bravais
lattice is defined by the crystal family and lattice system. Germanium for example, has a
face-centered diamond cubic structure.

* *Brillouin Zone* The first Brillouin zone is the locus of points in reciprocal
 space that are closer to the origin of the reciprocal lattice than they are to
 any other reciprocal lattice points.

* *Effective Mass* The mass a particle appears to have when responding to forces

* *Heavy and Light Holes* At the center of the first Brillouin zone, the (gamma point),
the two valence bands in Germanium meet. The shallower band is 'Heavy' as it has a
higher effect mass, meaning that it has a much larger density of states than that
of the lighter holes and therefore dominating the valence band.

== Equations





== Important Derivations
